
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
    networks:
      - frontend
      - backend

  caddy:
    image: caddy:2.10
    restart: unless-stopped
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      #- "80:80"
      - "443:8081"
      #- "443:443/udp"
    tmpfs:
      - /tmp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ${PWD}/conf/:/etc/caddy:ro
      # Allow CA root cert install (development only, remove for production env)
      - type: tmpfs
        target: /usr/local/share/ca-certificates
      - type: tmpfs
        target: /etc/ssl/certs
    links:
      - wordpress
    depends_on:
      - wordpress
    networks:
      - frontend
    read_only: true

  db:
    image: mysql:5.7
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data: { }
  wordpress: { }
  caddy_data: { }
  caddy_config: { }

networks:
    frontend: {}
    backend: {}